baseURL: 'https://majidb.ir/'
theme: PaperMod
defaultContentLanguage: fa

menu:
#  main:
#    - identifier: categories
#      name: categories
#      url: /categories/
#      weight: 10
#    - identifier: tags
#      name: tags
#      url: /tags/
#      weight: 20
#    - identifier: search
#      name: search
#      url: /search/
#      weight: 10

languages:
  fa:
    languageName: Persian
    languagedirection: rtl
    title: مجید بابایی
    author: مجید بابایی
    weight: 1
    keywords: [ وبلاگ, نمونه کار , آموزش , برنامه نویسی ]
    description: "برنامه نویس و توسعه دهنده"
    profileMode:
      enabled: true
      title: مجید بابایی
      subtitle: "برنامه نویس!"
      imageUrl: "me.jpg"
      imageWidth: 160
      imageHeight: 160
      imageTitle: مجید بابایی
      label:
        text: "صفحه اصلی"
      buttons:
        - name: بلاگ
          url: posts
        - name: درباره من
          url: about
  en:
    languageName: English
    description: "Full stack developer"
    title: Majid babaei
    author: Majid babaei
    weight: 2
    keywords: [ Blog, Portfolio , programming , tutorial ]
    label:
      text: "Home"
    profileMode:
      enabled: true
      title: Majid babaei
      subtitle: "Full stack developer"
      imageUrl: "me.jpg"
      imageWidth: 160
      imageHeight: 160
      imageTitle: Majid Babaeii
#      buttons:
#        - name: بلاگ
#          url: posts
#        - name: درباره من
#          url: about

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.

  images: [ ]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: icon.svg
    favicon16x16: icon.svg
    favicon32x32: icon.svg
    apple_touch_icon: icon.svg
    safari_pinned_tab: icon.svg


  socialIcons:
    - name: linkedin
      url: "https://www.linkedin.com/in/majid-babaei/"
    - name: github
      url: "https://github.com/majidbabaeii"
    - name: email
      url: "mailto:majid.babaeii70@gmail.com"

  analytics:
    google:
      SiteVerificationTag: "vOqO_Av5WXOlQ0tTOpCGvrj3zhEMnxwFnS9bb7RxpA8"
  #    bing:
  #      SiteVerificationTag: "XYZabc"
  #    yandex:
  #      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page
    linkFullImages: true

  editPost:
    URL: "https://github.com/majidbabaeii/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: [ "title", "permalink", "summary", "content" ]


googleAnalytics: UA-222423736-1


author:
  majid:
    name: "Majid"

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary